version: '3'
services:
  app:
    build: .
    command: python -u app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mongo:latest
    hostname: user_mongodb
    environment:
      - MONGO_INITDB_DATABASE=user_db
      - MONGO_INITDB_ROOT_USERNAME=usernme
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017